permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: David Li
  email: lidaweionline@gmail.com
  link: lidaweionline.com
  weibo: http://weibo.com/2642650177/
  github: http://github.com/lidaweionline/
# 站点信息
title: 李达伟的博客
description: My personal blog
url: http://lidaweionline.com

# gavatar头像及Favicon
gavatar: /public/img/monkey.png
favicon: /public/img/monkey.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: lidaweionline.com

# disqus 设置
disqus:
  shortname: lidaweionlinecom 

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
