baseurl:     /
url:         http://localhost:4000
source:      .
destination: ./_site
encoding:    utf-8
permalink:   /:title
highlighter: pygments
markdown:    rdiscount

#Basic Configuration
title:       lidaweionline | Know yourself

